name: build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - run: HOMEBREW_JDK=//opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home brew install --build-from-source -v pylucene
